name: Release
on:
  push:
    branches:
      - test
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH-KEY }}
      - name: Create test file
        run: |
          touch test_`date +%s`
      - name: Create branch commit and pull request in target repo
        id: create_pull_request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "chore: test"
          token: ${{ secrets.PAT }}
          base: main
          branch: test
          branch-suffix: short-commit-hash
          delete-branch: true
          title: Test PR
          body: This is just a test
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: branch_name
      - name: Add testing URL
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.PAT }}
          issue-number: ${{ steps.create_pull_request.outputs.pull-request-number }}
          body: "PR base: ${{ steps.branch_name.outputs.branch }}"
