name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH-KEY }}
      - name: Create test file
        run: |
          touch test_`date +%s`
      - name: Create branch commit and pull request in target repo
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "chore: test"
          token: ${{ secrets.PAT }}
          base: main
          branch: test
          branch-suffix: short-commit-hash
          delete-branch: true
          title: Test PR
          body: This is just a test
      - name: Add testing URL
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.PAT }}
          issue-number: ${{ steps.cpr.outputs.pull-request-number }}
          body: "PR base: ${{ github.event.pull_request.head.ref }}"
